[build]
  base = "."
  command = "npm run build && cp _redirects dist/public/_redirects"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"